In [1]:
import pandas
from datetime import date

In [2]:
data = pandas.read_csv("../Dataset/AlteredColumns.csv")

In [3]:
data.head(5)

,PeriodStart,AirTemp,CloudOpacity,DewpointTemp,Ghi,PrecipitableWater,RelativeHumidity,SurfacePressure,WindDirection10m,WindSpeed10m
0,2022-01-31T00:00:00Z,5.3,4.0,4.0,0,11.1,91.2,932.9,45,1.0
1,2022-01-31T00:05:00Z,5.3,3.5,3.9,0,11.2,91.1,933.0,45,1.0
2,2022-01-31T00:10:00Z,5.2,2.0,3.9,0,11.2,90.9,933.0,45,1.0
3,2022-01-31T00:15:00Z,5.2,0.4,3.8,0,11.2,90.8,933.0,45,1.0
4,2022-01-31T00:20:00Z,5.2,0.0,3.7,0,11.2,90.6,933.0,45,1.0

In [4]:
data["PeriodStart"]=data["PeriodStart"].astype(str)
data["PeriodStart"]=data["PeriodStart"].str.replace('T',' ')
data["PeriodStart"]=data["PeriodStart"].str.replace('Z','')
data.head(5)

,PeriodStart,AirTemp,CloudOpacity,DewpointTemp,Ghi,PrecipitableWater,RelativeHumidity,SurfacePressure,WindDirection10m,WindSpeed10m
0,2022-01-31 00:00:00,5.3,4.0,4.0,0,11.1,91.2,932.9,45,1.0
1,2022-01-31 00:05:00,5.3,3.5,3.9,0,11.2,91.1,933.0,45,1.0
2,2022-01-31 00:10:00,5.2,2.0,3.9,0,11.2,90.9,933.0,45,1.0
3,2022-01-31 00:15:00,5.2,0.4,3.8,0,11.2,90.8,933.0,45,1.0
4,2022-01-31 00:20:00,5.2,0.0,3.7,0,11.2,90.6,933.0,45,1.0

In [5]:
data["PeriodStart"]=pandas.to_datetime(data["PeriodStart"], format='%Y-%m-%d %H:%M:%S')
data.head(5)

,PeriodStart,AirTemp,CloudOpacity,DewpointTemp,Ghi,PrecipitableWater,RelativeHumidity,SurfacePressure,WindDirection10m,WindSpeed10m
0,2022-01-31 00:00:00,5.3,4.0,4.0,0,11.1,91.2,932.9,45,1.0
1,2022-01-31 00:05:00,5.3,3.5,3.9,0,11.2,91.1,933.0,45,1.0
2,2022-01-31 00:10:00,5.2,2.0,3.9,0,11.2,90.9,933.0,45,1.0
3,2022-01-31 00:15:00,5.2,0.4,3.8,0,11.2,90.8,933.0,45,1.0
4,2022-01-31 00:20:00,5.2,0.0,3.7,0,11.2,90.6,933.0,45,1.0

In [6]:
data["hour"] = data["PeriodStart"].map(lambda x: x.hour)
data["minutes"] = data["PeriodStart"].map(lambda x: x.minute)
data["day"] = data['PeriodStart'].map(lambda x: x.day)
data["month"] = data['PeriodStart'].map(lambda x: x.month)
data["year"] = data['PeriodStart'].map(lambda x: x.year)
data = data.drop(['PeriodStart'], axis=1)
data.head(5)

,AirTemp,CloudOpacity,DewpointTemp,Ghi,PrecipitableWater,RelativeHumidity,SurfacePressure,WindDirection10m,WindSpeed10m,hour,minutes,day,month,year
0,5.3,4.0,4.0,0,11.1,91.2,932.9,45,1.0,0,0,31,1,2022
1,5.3,3.5,3.9,0,11.2,91.1,933.0,45,1.0,0,5,31,1,2022
2,5.2,2.0,3.9,0,11.2,90.9,933.0,45,1.0,0,10,31,1,2022
3,5.2,0.4,3.8,0,11.2,90.8,933.0,45,1.0,0,15,31,1,2022
4,5.2,0.0,3.7,0,11.2,90.6,933.0,45,1.0,0,20,31,1,2022